/***********************************************************************************************************************************
* Copyright © 2021 Creditas
* ================================================================================================================================
* @description Handler padrão para a trigger do Objeto Documentos (Documents).
* ================================================================================================================================
* History
* -------
* VERSION   AUTHOR                  DATE            DETAIL      Description
* 1.0       Thales Yumiya           13/08/2021      Created     Implementação de handler voltado para uso da Trigger do objeto Documentos (Documents)
**********************************************************************************************************************************/
public without sharing class DocumentsTriggerHandler extends TriggerHandler
{
    //DELETED
}