/***********************************************************************************************************************
 * Copyright © 2021 Creditas
 * =======================================================================================================================
 * @description Picklist values for Opportunity FromalizationStatus field
 * 
 =======================================================================================================================
 * History
 * -------
 * VERSION   AUTHOR                  DATE            DETAIL      Description
 * 1.0       Matheus Fernandes       15/02/2021      Created     Class creation
 **********************************************************************************************************************/
public class OpportunityFormalizationStatus {
    public static final String NEW_PROPOSAL = 'NewProposal';
    public static final String AWAITING_ANALYSIS = 'AwaitingAnalysis';
    public static final String UNDER_ANALYSIS = 'UnderAnalysis';
    public static final String APPROVED = 'Approved';
    public static final String REJECTED = 'Rejected';
    public static final String PENDING = 'Pending';
}
